name: DyableBossBars
version: '${project.version}'
main: adhdmc.dyablebossbars.DyableBossBars
api-version: 1.18
authors: [_Rhtyhmic]
description: Dye Boss Bars different colors! https://github.com/RhythmicSys/DyableBossBars
permissions:
  dyablebossbars.dye.red:
    description: Allow player to dye bossbars red
    default: op
  dyablebossbars.dye.yellow:
    description: Allow player to dye bossbars yellow
    default: op
  dyablebossbars.dye.green:
    description: Allow player to dye bossbars green
    default: op
  dyablebossbars.dye.blue:
    description: Allow player to dye bossbars blue
    default: op
  dyablebossbars.dye.purple:
    description: Allow player to dye bossbars purple
    default: op
  dyablebossbars.dye.pink:
    description: Allow player to dye bossbars pink
    default: op
  dyablebossbars.dye.white:
    description: Allow player to dye bossbars white
    default: op
  dyablebossbars.dye.*:
    description: Allow player to dye bossbars any color
    default: op
    children:
      dyablebossbars.dye.red: true
      dyablebossbars.dye.yellow: true
      dyablebossbars.dye.green: true
      dyablebossbars.dye.blue: true
      dyablebossbars.dye.purple: true
      dyablebossbars.dye.pink: true
      dyablebossbars.dye.white: true
